[package]
name = "picipaint"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = { version = "0.30.0", default-features = false, features = ["default_fonts", "glow", "x11", "wayland"] }

[dev-dependencies]
approx = "0.5.1"
mockall = "0.13.1"
