[package]
name = "picipaint"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = { version = "0.30.0" }
image = "0.25.5"

[dev-dependencies]
approx = "0.5.1"
mockall = "0.13.1"

[profile.release]
panic = "abort"
lto = "thin"
