[package]
name = "picipaint"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe  = "0.30.0"
egui_extras = { version = "0.30.0", features = ["all_loaders"] }
image = "0.25.5"
rfd = "0.15.3"

[profile.release]
panic = "abort"
lto = "thin"
