name: Build and create release

on:
  push:
    tags:
    - 'v*'

jobs:
  build-linux:
    runs-on: ubuntu-24.04
    steps:
    - name: install dependencies of raylib
      run: sudo apt install libasound2-dev libx11-dev libxrandr-dev libxi-dev libgl1-mesa-dev libglu1-mesa-dev libxcursor-dev libxinerama-dev libwayland-dev libxkbcommon-dev
    - name: install dependencies of nativefiledialog-extended
      run: sudo apt install libgtk-3-dev
    - name: checkout sources
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: build
      run: make
    - name: create release
      uses: softprops/action-gh-release@v2
      with:
        files: bin/picipaint
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build-windows:
    runs-on: windows-latest
    steps:
    - name: checkout sources
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: build
      run: |
        $env:PATH = "C:\mingw64\bin;$env:PATH"
        make
      env:
        CC: gcc
    - name: create release
      uses: softprops/action-gh-release@v2
      with:
        files: bin/picipaint.exe
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
