name: Build and create release

on:
  push:
    branches: main
    #tags:
    #- 'v*'

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - name: install Windows cross compiler
      run: sudo apt install gcc-mingw-w64
    - name: install dependencies of raylib
      run: sudo apt install libasound2-dev libx11-dev libxrandr-dev libxi-dev libgl1-mesa-dev libglu1-mesa-dev libxcursor-dev libxinerama-dev libwayland-dev libxkbcommon-dev
    - name: install dependencies of nativefiledialog-extended
      run: sudo apt install libgtk-3-dev
    - name: checkout sources
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: build Linux binary
      run: make
      env:
        CC: gcc-14
        BIN_DIR: bin/linux/
    - name: build Windows binary
      run: |
        make clean_all
        make
      env:
        CC: x86_64-w64-mingw32-gcc
        BIN_DIR: bin/windows/
    #- name: create release
    #  uses: softprops/action-gh-release@v2
    #  with:
    #    files: bin/picipaint
    #  env:
    #      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
