name: Build and create release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          override-with: rustup

      - name: Build the application
        run: cargo build --release

      - name: Prepare binaries
        run: |
          mkdir -p output
          if [[ "$RUNNER_OS" == "Linux" ]]; then
            cp target/release/picipaint output/picipaint_linux
          elif [[ "$RUNNER_OS" == "Windows" ]]; then
            cp target/release/picipaint.exe output/picipaint_windows.exe
          fi
        shell: bash

      - name: Upload Linux artifact
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@v4
        with:
          name: linux-binaries
          path: output/

      - name: Upload Windows artifact
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v4
        with:
          name: windows-binaries
          path: output/

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download Linux artifacts
        uses: actions/download-artifact@v4
        with:
          name: linux-binaries

      - name: Download Windows artifacts
        uses: actions/download-artifact@v4
        with:
          name: windows-binaries

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            linux-binaries/picipaint_linux
            windows-binaries/picipaint_windows.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
